language: python
python:
        - "3.6"
install:
        - pip install pipenv
        - pipenv install
script:
        - pipenv run nosetests --with-coverage --cover-erase --cover-package=heimdall --cover-html
        - pipenv run coverage-badge -o coverage
