language: python
python:
        - "3.6"
install:
        - pip install pipenv
        - pipenv install
script:
        - pipenv run coverage run -m unittest discover -s test/ -vv

deploy:
        provider: heroku
        api_key:
                secure: "ffaff4c9-6cb4-41d0-84ed-795d962ed006"
        strategy: git

after_deploy:
        - pipenv run python main.py xkcd & disown
        - pipenv run python main.py queer & disown
        - pipenv run python main.py music & disown
